# Generated by Django 5.2.11 on 2026-02-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member'), ('VIEWER', 'Viewer')], default='OWNER', max_length=20),
        ),
    ]
