# Generated by Django 5.2.11 on 2026-02-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_due_date_todo_is_deleted_todo_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltodo',
            name='parent_todo',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Reference to the original recurring todo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='todos.todo'),
        ),
        migrations.AddField(
            model_name='historicaltodo',
            name='recurrence_type',
            field=models.CharField(choices=[('NONE', 'No Recurrence'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='parent_todo',
            field=models.ForeignKey(blank=True, help_text='Reference to the original recurring todo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_instances', to='todos.todo'),
        ),
        migrations.AddField(
            model_name='todo',
            name='recurrence_type',
            field=models.CharField(choices=[('NONE', 'No Recurrence'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='action',
            field=models.CharField(choices=[('STATUS_CHANGE', 'Status Changed'), ('ASSIGNEE_CHANGE', 'Assignee Changed'), ('DUE_DATE_CHANGE', 'Due Date Changed'), ('TITLE_CHANGE', 'Title Changed'), ('DESCRIPTION_CHANGE', 'Description Changed'), ('CREATED', 'Created'), ('DELETED', 'Deleted'), ('UPDATED', 'Updated')], max_length=20),
        ),
    ]
