# Generated by Django 4.2.28 on 2026-02-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_historicaltodo_parent_todo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditTrail',
        ),
    ]
