# Generated by Django 4.2.28 on 2026-02-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_organization_role_client_keycloak_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='keycloak_id',
            new_name='keycloak_client_id',
        ),
        migrations.AddField(
            model_name='client',
            name='keycloak_group_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
