# Generated by Django 4.2.28 on 2026-02-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_keycloak_id_client_keycloak_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('TENANT_CREATED', 'Tenant Created'), ('TENANT_DELETED', 'Tenant Deleted'), ('USER_DELETED', 'User Permanently Deleted'), ('USER_DISABLED', 'User Disabled'), ('METRICS_REFRESH', 'Dashboard Metrics Refresh'), ('RECURRING_TODO', 'Recurring Todo Processing')], max_length=50)),
                ('tenant_name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20)),
                ('triggered_by', models.CharField(blank=True, max_length=100, null=True)),
                ('flow_run_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['tenant_name'], name='customers_s_tenant__582290_idx'), models.Index(fields=['operation'], name='customers_s_operati_746a7b_idx'), models.Index(fields=['started_at'], name='customers_s_started_0528fb_idx')],
            },
        ),
    ]
